#!/usr/bin/env bash
#Configures nginx to a brand new server 
apt-get update
apt-get -y install nginx
systemctl start nginx
ufw allow 'Nginx HTTP'
bash -c "echo 'Hello Word!' > /var/www/html/index*.html"
