#!/usr/bin/env bash
#Configures nginx to a brand new server 
apt-get update
apt-get -y install nginx
systemctl start nginx
ufw allow 'Nginx HTTP'
bash "echo 'Hello word!' > /var/www/html/index*.html"
