#!/usr/bin/env bash
# usign the private key location to connect to the server and configure the header
comment="#This customs the header by adding one more information"
line="add_header Served-By $HOSTNAME;"
previous="location \/ {"
replace="location \/ {\\n\\t\\t$comment\\n\\t\\t$line"
location="/etc/nginx/sites-enabled/default"
apt-get install nginx
sed -i "s/$previous/$replace/" $location
