#!/usr/bin/env bash
#Configures the environment : modeifies the the hostname and facebook ips
cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/g' ~/hosts.new
sed -i 's/157.240.11.35/8.8.8.8/g' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
